apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment
  name: serv
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: deployment
  type: NodePort
status:
  loadBalancer: {}
